# Generated by Django 3.2 on 2022-08-13 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, verbose_name='Name')),
                ('email', models.CharField(max_length=225, verbose_name='Email')),
                ('status', models.CharField(choices=[('blank', 'Blank'), ('voted', 'Voted')], max_length=10, verbose_name='Status')),
                ('invitation_code', models.CharField(max_length=225, verbose_name='Invitation Code')),
                ('related_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
    ]
